name: Render Thesis

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt-get
      run: |
        sudo apt-get update && \
        sudo apt-get install \
                      texlive texlive-fonts-extra texlive-science \
                      -y
    #- name: Tag
    #  run: |
    #    sed -i "s/^\\\\copyrighttext{All Rights Reserved}$/\\\\copyrighttext{All Rights Reserved \\\\\\\\ TO""DO: this is a draft \\\\\\\\ commit sha: `git rev-parse HEAD` \\\\\\\\ build date: `date`}/" thesis.tex
    - name: Build
      run: |
        make
    - name: Release
      uses: actions/upload-artifact@v3
      with:
        name: thesis
        path: |
          thesis.pdf
    - uses: actions/checkout@v3
      with:
        ref: pdf
        path: pdf
    - name: Push
      run: |
        REF_NAME="`echo $GITHUB_REF_NAME | sed 's|/|-|g'`"
        ln -f thesis.pdf pdf/thesis-"$REF_NAME".pdf
        cd pdf
        git add thesis-"$REF_NAME".pdf
        git config user.email "actions@git.hub"
        git config user.name "GitHub Actions"
        git commit -m "Auto generated from $REF_NAME $GITHUB_SHA"
        git push
        git log -1

